# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '\u53cb\u60c5\u94fe\u63a5', 'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5'},
        ),
        migrations.AddField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '\u5c55\u793a'), (2, '\u4e0b\u9650')], default=1, verbose_name='\u4e0a\u4e0b\u7ebf\u72b6\u6001'),
        ),
    ]
